# Generated by Django 3.1.7 on 2021-04-03 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('ref', models.CharField(max_length=50)),
                ('qty', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Engin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('desi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.designation')),
            ],
        ),
    ]
